1.Split this string.

In [1]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string
Output should be:


The diameter of Earth is 12742 kilometers

In [2]:
planet = "Earth"
diameter = 12742
print('The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word "hello"

In [5]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]["target"][3])

hello


Numby

import numby as np

4.1 create an array of 10 zeros?

In [7]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 create an array  of 10 fives?

In [9]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5.Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


6.Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.Concatenate a and b

a=np.array([1,2,3]),b=np.array([4,5,6])

In [13]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


pandas

8.Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd
data=[10,20,30]
df=pd.DataFrame(data,columns=['Numbers'])
df

Numbers
0       10
1       20
2       30

9.Create the series of dates from 1st Jan,2023 to 10th Feb,2023

In [17]:
import pandas as pd
dRan=pd.date_range(start='1-1-2023',end='10-2-2023',freq='M')
print(dRan)

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')


10.Create 2D list to DataFrame

In [20]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['Number','Letter','Age'],dtype=int)
print(df)

   Number Letter  Age
0       1    aaa   22
1       2    bbb   25
2       3    ccc   24


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
